stages:
  train:
    cmd: python3 deepl.py 50
    deps:
    - real-or-fake-fake-jobposting-prediction.zip
    outs:
    - model
  evaluate:
    cmd: python3 evaluation.py
    deps:
    - model
    outs:
    - metrics.png
    - metrics.txt
